# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0002_user_course_progress_progress_reached'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course_progress',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
