# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0003_user_course_progress_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
