# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0004_course_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
