# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0005_auto_20170103_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_slug',
            new_name='slug',
        ),
    ]
