# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0006_auto_20170104_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
