# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_registration', '0008_auto_20170109_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='seats_cur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='seats_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
