# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0010_user_course_registration_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_course_registration',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user_course_progress',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
