# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0011_auto_20170117_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_registration',
            field=models.BooleanField(default=True),
        ),
    ]
