# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0012_course_course_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_active',
            field=models.BooleanField(default=True),
        ),
    ]
