# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0014_remove_course_seats_cur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_course_progress',
            name='active',
        ),
    ]
