# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0016_course_iteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_progress',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_registration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats_max',
        ),
    ]
