# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0019_user_course_registration_iteration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_iteration',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
