# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0020_course_iteration_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_course_registration',
            name='course_id',
        ),
    ]
