# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0021_remove_user_course_registration_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course_registration',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_registration.Course'),
            preserve_default=False,
        ),
    ]
