# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0022_user_course_registration_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_choice_values',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
