# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0023_field_field_choice_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('EmailField', 'EmailField'), ('BooleanField', 'BooleanField'), ('IntegerField', 'IntegerField'), ('ChoiceField', 'ChoiceField')], max_length=200),
        ),
    ]
